<?php
header('Content-type:text/html;charset=utf-8');
$userName=$_POST['userName'];
$commont=$_POST['commontContent'];
$songName=$_POST['songName'];
$singerName=$_POST['singerName'];
$dateTime=$_POST['dateTime'];
$servername="localhost";
$username="root";
$password="Cong19960623";
$dbname="musiccommont";
$count=0;
$conn=mysqli_connect($servername,$username,$password,$dbname);
if(!$conn){
	die("fail".mysqli_connect_error());
}
$sql="INSERT INTO commont(song_name,singer_name,user_name,content,commont_time,point_number) VALUES ('$songName','$singerName','$userName','$commont','$dateTime','$count')";
       $result=mysqli_query($conn,$sql);
mysqli_close($conn);
?>